import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-GB">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-200 text-gray-900 font-mono`}
      >
        <div className="flex flex-col min-h-screen max-w-[1500px] mx-auto bg-white shadow-2xl">
          
          <Navbar />
          <main className="flex-1 w-full px-4 md:px-8 py-6 pt-32 md:pt-24">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}